default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: localhost
  port: 3306

development:
  <<: *default
  database: db_ecommerce

test:
  <<: *default
  database: db_ecommerce

production:
  <<: *default
  database: db_ecommerce